### ISSUE TITLE
Using BlockSDK in Marketing cloud.

### ISSUE THREAD

**Issue by sasha-qred** [salesforce-marketingcloud/blocksdk#2]
Is it possible for now to use BlockSDK and custom block in MarketingCloud?

I have implemented my own application:
This app works in [blocktester](https://blocktester.herokuapp.com/)
But 
Does not in MarketingCloud.

In addition, I deployed the [sampleblock](https://github.com/tbesluau/sampleblock) to Heroku but I see the same issue:
It does not work in MarketingCloud.

After debugging and modifying the source code of SDK I found the issue. Parent window in MarketingCloud doesn't answer on `handShake`.

In my local project, I have changed the code of SDK. And after that my custom block starts working in MarketingCloud.

``` diff
  this._postToEditor = function (payload, callback, ttl) {
    var self = this;
-    // we only message up if we have
-    // validated the origin
-    if (!this._parentOrigin) {
-      if (ttl === undefined || ttl > 0) {
-        window.setTimeout(function () {
-          self._postToEditor(payload, callback, (ttl || 5) - 1);
-        }, 20);
-      }
-      return;
-    }
    this._messages[this._messageId] = callback;
    payload.id = this._messageId;
    this._messageId += 1;
    // the actual postMessage always uses
    // the validated origin
-    window.parent.postMessage(payload, this._parentOrigin);
+    window.parent.postMessage(payload, '*');
  };
```

**Comment by dowenssfmc** [comment]
Hello. It will not be possible to add your block to the Marketing Cloud until the April 21 release.
